### PR TITLE
Add database schema test and associated rule

### PR DESCRIPTION
**Pull request by strk**
Fixes: #181

### CODE REVIEW

**Comment by strk** [comment]
On github-actions I get `the input device is not a TTY`, rings a bell, but I don't remember how we fixed that in another case.
@SPlanzer do you recall that message ?

**Comment by SPlanzer** [comment]
> On github-actions I get `the input device is not a TTY`, rings a bell, but I don't remember how we fixed that in another case.
> @SPlanzer do you recall that message ?

Yeah sure do. 


b303d7bbdd32fa0c7ed23509d9bf57ccb3bc280f got these passing

**Review by SPlanzer — APPROVED** [review]
LGTM - Testing are hanging due to my issue (#185).

I will resolve this today and once tests pass we can merge in

**Comment by strk** [comment]
Unfortunately the error here is still `the input device is not a TTY`, nothing to do with the hanging, I've to figure out why `pg_tap` wants a TTY...

**Comment by strk** [comment]
It looks like adding `-T` switch to `docker-compose exec` fixes the TTY problem. Now to find out why the tests fail.

**Comment by strk** [comment]
Ok the failure was due to wrong assumption about where `gaz_update_export_database` function should be (test expected it in `gazetteer_export` schema, but in reality it is in `gazetteer`). I'm not sure where it shoudl be, as the `CREATE FUNCTION` is not qualified here:
> src/sql/gazetteer_export_func.sql:CREATE OR REPLACE FUNCTION gaz_update_export_database()

There's a search_path set at the beginning of the file, which was changed by @SPlanzer in 0b43c3afd0ff2e4936d8627320d5ec3ea50e7995 to have `gazetteer` as the first schema, instead of `gazetteer_export`, which one would be more correct ?

Note the other error was `name_export_for_lol` being also in `gazetteer` schema, but maybe that one should also be in `gazetteer_export` ?

Anyway for now I made the tests pass with what we have..

**Comment by strk** [comment]
Ok I think we have a problem. The tests fail on my machine, as I invoke `make docker-db-tests` directly, from the starting docker images. But it succeeds here, so my impression is that some views/functions are created by precedent tests (qgis tests?). I suspect this is something that should not happen (leaving artifacts by the end of tests)

**Comment by strk** [comment]
Ok I was wrong, I just had to rebuild the docker image. Tests pass on my machine as well now.

**Pull request merged**
