### PR TITLE
Src code reformatting

### PR DESCRIPTION
**Pull request by SPlanzer**
Fixes: #  
* Adheres to Black formatting #52
* Removes trailing white space

### Change Description:

...

### Notes for Testing:

...

#### Source Code Documentation Tasks:
- [ ] README updated (where applicable)
- [ ] CHANGELOG updated

#### User Documentation Tasks:
- [ ] Confluence user guide updated (where applicable)

#### Testing Tasks:
- [ ] Added tests that fail without this change
- [ ] All tests are passing in development environment
- [ ] Reviewers assigned

#### Pull Request Management: 
- [ ] Linked to sub-task
- [ ] Linked to the epic

### CODE REVIEW

**Comment by SPlanzer** [comment]
@strk can I please have your review

It is just black formatting and white space removal.

**Comment by strk** [comment]
I dubt there's much I can review, if it's just formatting.
Just make sure formatting is retained by using a proper github action (and ideally add a Makefile target to perform that same formatting, so I can check I can run that target and see NO change in this branch)

**Comment by SPlanzer** [comment]
> I dubt there's much I can review, if it's just formatting.
> Just make sure formatting is retained by using a proper github action (and ideally add a Makefile target to perform that same formatting, so I can check I can run that target and see NO change in this branch)

I have updated the makefile to run formatting validation and formatting cleaning for trailing whitespace and python Black. 

Note. CI also runs these checks on push

**Comment by strk** [comment]
I cannot install tools to ensure formatting:

```
[strk@liz:/usr/src/linz/gazetteer/gazetteer(src_code_reformatting)] python --version
Python 2.7.17
[strk@liz:/usr/src/linz/gazetteer/gazetteer(src_code_reformatting)] pip install -r requirements-dev.txt 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting gitlint==0.13.1
  Using cached gitlint-0.13.1-py2.py3-none-any.whl (74 kB)
ERROR: Could not find a version that satisfies the requirement pre-commit==2.1.1 (from -r requirements-dev.txt (line 2)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.13.0, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.15.0, 1.15.1, 1.15.2, 1.16.0, 1.16.1, 1.17.0, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.19.0, 1.20.0, 1.21.0)
ERROR: No matching distribution found for pre-commit==2.1.1 (from -r requirements-dev.txt (line 2))
```

**Comment by SPlanzer** [comment]
> I cannot install tools to ensure formatting:
> 
> ```
> [strk@liz:/usr/src/linz/gazetteer/gazetteer(src_code_reformatting)] python --version
> Python 2.7.17

Gaz is using python 3.6

**Comment by strk** [comment]
My setup with gitlint is broken due to https://github.com/jorisroovers/gitlint/issues/127 I'll file a PR

**Pull request merged**
