### PR TITLE
Remerge missing code

### PR DESCRIPTION
**Pull request by billgeo**
Master branch has code missing from March 2020 to this commit

### CODE REVIEW

**Comment by billgeo** [comment]
@SPlanzer I've got it to a state where the pull_request CI tests are passing. Can you please review and approve and I'll create another PR with @iharrison's changes.

FYI - I've created a master-backup branch

**Comment by palmerj** [comment]
@billgeo so was it non-ASCII causing the issues from CI passing yesterday then?

**Comment by billgeo** [comment]
Not sure @palmerj . I think it was maybe something to do with cherry picking from master and then trying to merge the same commit back into master.

**Comment by billgeo** [comment]
Is should also have mentioned that I am planning to remerge this one later.

https://github.com/linz/gazetteer/pull/233

**Review by SPlanzer — APPROVED** [review]
LGTM

**Pull request merged**
