### PR TITLE
Fix install web db startup

### PR DESCRIPTION
**Pull request by SPlanzer**
fixes issue arising with docker-compose and install_web.sh. see #93

### CODE REVIEW

**Comment by strk** [comment]
Was this PR meant to be based on 2to3 branch ? Because it contains SO MANY changes...

**Comment by strk** [comment]
I rebased this PR to the 2to3 branch, so it is clear what you actually want a review of, @SPlanzer.
That said, that branch is blowing up, we should try to merge what's completed to avoid maintaining such big change branches....

Specifically to this change request, I see 2 changes being made:

   1. Addressing a QGIS branch rather than QGIS tag (makes builds less predictable)
   2. Adding a sleep() somewhere (makes build less predictable)

I've to say I dislike both of them. Could you please file tickets to let me know what's the actual problem you were trying to solve ? If I'm not wrong github-action is supposed to be building those docker images on every push to the PR-attached branch...

**Comment by SPlanzer** [comment]
> Was this PR meant to be based on 2to3 branch ? Because it contains SO MANY changes...

it is suppose to be based on 2to3 branch. I am attempting to resolve issues I am having with docker-compose and evaluating the ported plugin against it

**Comment by SPlanzer** [comment]
> I rebased this PR to the 2to3 branch, so it is clear what you actually want a review of, @SPlanzer.
> That said, that branch is blowing up, we should try to merge what's completed to avoid maintaining such big change branches....

I agree 

> Specifically to this change request, I see 2 changes being made:
> 
>     1. Addressing a QGIS branch rather than QGIS tag (makes builds less predictable)
> 
>     2. Adding a sleep() somewhere (makes build less predictable)
> 
> 
> I've to say I dislike both of them. Could you please file tickets to let me know what's the actual problem you were trying to solve ? If I'm not wrong github-action is supposed to be building those docker images on every push to the PR-attached branch...

this is related to issues #92 and #93. These are related to issues I am having with docker-compose locally.

**Comment by SPlanzer** [comment]
agreed. This is a poor fix

**Pull request closed without merging**
