### PR TITLE
Target QGIS 3.12

### PR DESCRIPTION
**Pull request by strk**
Use the 3.12 version of QGIS docker image.
This is mostly to see if we can remove the monkey patch
of testrunner

### CODE REVIEW

**Comment by SPlanzer** [comment]
It would be great if we could remove the monkey patching of the test runner. 

What are your thoughts of using 3.12 for automated tests when the software is going to be deployed against the LTR 3.10? I would expect 100% compatibility between the versions but I and expect others would be much more comfortable with using 3.10 if that is what the release will be against

**Comment by billgeo** [comment]
I think we'd be okay to do this for something like the Gazetteer. But should expect the odd bug to come in from the NZGB team because of this.

**Comment by strk** [comment]
On Wed, Jun 17, 2020 at 01:56:28PM -0700, Simon Planzer wrote:
> It would be great if we could remove the monkey patching of the test runner. 

Yes, that's my thought. Only I've been having troubles finding
instructions to reproduce the bug which made us using the monkey-patch
in the first place. Do you have a link to the corresponding ticket ?

It doesn't help that my `make docker-qgis-start` command does NOT
always succeed in showing the qgis window (often I get decorations
but no content of windows, and trying to debug that).

> What are your thoughts of using 3.12 for automated tests when the software is going to be deployed against the LTR 3.10? I would expect 100% compatibility between the versions but I and expect others would be much more comfortable with using 3.10 if that is what the release will be against

For tests we'd ideally use BOTH 3.10 and 3.12

**Comment by strk** [comment]
Monkey patching removed. If it works, this is a good step toward testing multiple versions of things.
@billgeo this includes testing PostgreSQL-12, for example

**Review by billgeo — APPROVED** [review]
Thanks @strk, I'm okay with this as long as we can still test QGIS 3.10 adequately.

I don't have any comments on the code changes or style. But if you are happy this is working okay, I think it will be fine to merge it.

**Pull request merged**
