### PR TITLE
trim trailing whitespace from plugin python sources

### PR DESCRIPTION
**Pull request by strk**
Respects editorconfig

### CODE REVIEW

**Comment by strk** [comment]
The EditorConfig action from marketplace is too expensive, BUILDS a docker to run that simple check, really not that ideal. Better get back to simple checking... (see https://github.com/linz/gazetteer/runs/536081065)

**Comment by SPlanzer** [comment]
Ive made a number of changes in branch 2to3 that I'm guessing will conflict. I will run these through black to tidy up white spaces.

**Comment by strk** [comment]
Big improvement here is the CI testing for blanks not to come back, if you enable that test in your branch and ensure is passes, I'm happy to close this. But note I did this because any file I'd touch would otherwise be changed to match editorconfig recommendations and this means my changes would be a mix of style and functional changes. The goal here was to keep those commits separated.

**Comment by SPlanzer** [comment]
> Big improvement here is the CI testing for blanks not to come back, if you enable that test in your branch and ensure is passes, I'm happy to close this. But note I did this because any file I'd touch would otherwise be changed to match editorconfig recommendations and this means my changes would be a mix of style and functional changes. The goal here was to keep those commits separated.

This would have been best practice. Unfortunately I have made many functional code changes to the same files. I will added the CI into my branch and get this merged ASAP.

**Comment by strk** [comment]
@SPlanzer did you port the workflow in your PR yet ? Let me know if so, then we can close this one

**Comment by SPlanzer** [comment]
> @SPlanzer did you port the workflow in your PR yet ? Let me know if so, then we can close this one

I have added it to .github/workflows/push.yml but commented it out as there needs to be a piece of work to solve formatting issues. This will be the next task. 

Based on this I think we can close this

**Comment by strk** [comment]
Ok, closing, thanks

**Pull request closed without merging**
