### PR TITLE
Add PostgreSQL 12 support

### PR DESCRIPTION
**Pull request by strk**
Provide makefile targets to build db version 12 (with postgis 3.0)

### CODE REVIEW

**Review by SPlanzer — APPROVED** [review]
looks good

**Comment by billgeo** [comment]
Thanks @strk so will you do another PR to fix the test_docker tests?

**Comment by strk** [comment]
All tests will need to be fixed before we can possibly merge this

**Comment by billgeo** [comment]
> All tests will need to be fixed before we can possibly merge this

Are you able to estimate how much work it is to complete this PR? Roughly.

**Comment by strk** [comment]
The docker tests succeded, so we're likely close

**Comment by strk** [comment]
Good news: it looks like there's nothing to do for supporting PostgreSQL 12!

**Comment by billgeo** [comment]
> Good news: it looks like there's nothing to do for supporting PostgreSQL 12!

Woohoo! Thanks so much for doing this @strk

**Pull request merged**
