### PR TITLE
geoalchemy2 src code

### PR DESCRIPTION
**Pull request by SPlanzer**
Fixes: #
* #189 Include geoalchemy2 src code in release

### Notes for Testing:
As per #189 test are required to pass without sqlalchemy and geoalchemy2 in requirements.txt

#### Source Code Documentation Tasks:
- [ ] README updated (where applicable)
- [ ] CHANGELOG updated

#### User Documentation Tasks:
- [ ] Confluence user guide updated (where applicable)

#### Testing Tasks:
- [ ] Added tests that fail without this change
- [ ] All tests are passing in development environment
- [ ] Reviewers assigned

#### Pull Request Management:
- [ ] Linked to sub-task
- [ ] Linked to the epic

### CODE REVIEW

**Comment by strk** [comment]
I don't like the idea of importing external code into the git repository. Rather, inclusion should be done at release time (do we have a Makefile target to create a release?). Alternatively it could maybe be a git submodule ?

**Comment by SPlanzer** [comment]
agreed - I will have the github actions install these at release

**Comment by SPlanzer** [comment]
Closed by #195

**Comment by strk** [comment]
Closing as per last comment

**Comment by strk** [comment]
@SPlanzer I guess the branch can be deleted ? (doing some cleanups)

**Pull request closed without merging**
