### PR TITLE
Remove carriage returns from SQL files

### PR DESCRIPTION
**Pull request by strk**
Should help future formatting

### CODE REVIEW

**Comment by SPlanzer** [comment]
There are some aspects of this I am still not clear on after reading the documentation. 

Mainly, for this tool to be effective it will need to be executed on each commit in github. I would normally integrate this with github actions however as far as I can see this tool has no CLI. 

What is the best way to ensure all code committers are using this?

**Comment by billgeo** [comment]
@SPlanzer have you seen this https://github.com/marketplace/actions/editorconfig-action?

**Comment by strk** [comment]
This PR is not aimed at _enforcing_ a specific format, just:

  1. Document what we want
  2. Allow developers to configure their editor to follow the recomendation

The above is what Editorconfig does.

Enforcing the format was out of scope here, as well as checking if the current format matches what we want. But they are both (in reverse order) good follow up steps.

**Comment by strk** [comment]
Ok I changed scope if this PR to only remove carriage returns from files, filing another PR to add the .editorconfig file to document that's what we want (##71)

**Comment by strk** [comment]
Let's simplify things: #72 includes this so will close this PR

**Pull request closed without merging**
